//! Integration tests for the current Rust code generator.
//!
//! These tests use pre-generated Rust code from vest files located in `tests/emitted/`.
//! To regenerate the emitted files, run:
//!   cargo run -- tests/vest_files/combined.vest -o tests/emitted/combined.rs
//!   cargo run -- tests/vest_files/tlv.vest -o tests/emitted/tlv.rs

mod emitted;

use emitted::combined;
use emitted::tlv;
// use emitted::tls;
use vest_lib::properties::*;

#[test]
fn combined_generate_serialize_parse_roundtrip() {
    for seed in 0..16u64 {
        let (reported_len, value): (usize, combined::Packet) =
            combined::generate_Packet(&mut GenSt::new(seed)).expect("generate packet");

        let payload_len = value.payload_len as usize;
        assert_eq!(
            payload_len,
            value.payload.len() * 8,
            "seed {seed}: payload_len should equal the serialized record bytes",
        );

        let computed_len = combined::Packet_len(&value);
        assert_eq!(
            reported_len, computed_len,
            "seed {seed}: generated byte count should match combinator length",
        );

        let mut buf = vec![0u8; computed_len];
        let written = combined::serialize_gen_Packet(value, &mut buf, 0).expect("serialize packet");
        assert_eq!(written, computed_len);
        assert_eq!(
            &buf[..2],
            &[0xFE, 0xCA],
            "seed {seed}: current DSL lowering emits the magic tag in little endian",
        );

        let (consumed, parsed) = combined::parse_Packet(&buf).expect("parse packet");
        assert_eq!(consumed, written);
        // assert_eq!(parsed, value);
    }
}

#[test]
fn tlv_msg_generate_roundtrip() {
    for seed in 0..16u64 {
        let (reported_len, msg) = tlv::generate_msg(&mut GenSt::new(seed)).expect("generate msg");

        let mut buf = vec![0u8; reported_len];
        let written = tlv::serialize_gen_msg(msg, &mut buf, 0).expect("serialize msg");
        assert_eq!(written, reported_len);

        let (consumed, parsed) = tlv::parse_msg(&buf).expect("parse msg");
        assert_eq!(consumed, written);

        let computed_len = tlv::msg_len(&parsed);
        assert_eq!(
            reported_len, computed_len,
            "seed {seed}: generated byte count should match combinator length",
        );
    }
}

// #[test]
// fn tls_msg_generate_roundtrip() {
//     for seed in 0..16u64 {
//         let (reported_len, handshake) = tls::generate_handshake(&mut GenSt::new(seed)).expect("generate handshake");

//         let mut buf = vec![0u8; reported_len];
//         let written = tls::serialize_gen_handshake(handshake, &mut buf, 0).expect("serialize handshake");
//         assert_eq!(written, reported_len);

//         let (consumed, parsed) = tls::parse_handshake(&buf).expect("parse handshake");
//         assert_eq!(consumed, written);
//         // assert_eq!(parsed, msg);
//     }
// }